import type { Company } from "./types";

export const companies: Company[] = [
  { t: "RELIANCE", n: "Reliance Industries", c: "#00529b", logo: "RELIANCE.png", p: 1300 },
  { t: "TCS", n: "Tata Consultancy Services", c: "#5f259f", logo: "TCS.png", p: 3800 },
  { t: "HDFCBANK", n: "HDFC Bank", c: "#004c8f", logo: "HDFCBANK.png", p: 1650 },
  { t: "INFY", n: "Infosys", c: "#007cc3", logo: "INFY.png", p: 1550 },
  { t: "ICICIBANK", n: "ICICI Bank", c: "#f37021", logo: "ICICIBANK.png", p: 1250 },
  { t: "HINDUNILVR", n: "Hindustan Unilever", c: "#2d9cdb", logo: "HINDUNILVR.png", p: 2350 },
  { t: "ITC", n: "ITC Ltd", c: "#005c8f", logo: "ITC.png", p: 430 },
  { t: "SBIN", n: "State Bank of India", c: "#2f80ed", logo: "SBIN.png", p: 780 },
  { t: "LT", n: "Larsen & Toubro", c: "#f2c94c", logo: "LT.png", p: 3500 },
  { t: "BHARTIARTL", n: "Bharti Airtel", c: "#eb5757", logo: "BHARTIARTL.png", p: 1650 },
  { t: "KOTAKBANK", n: "Kotak Mahindra Bank", c: "#bb6bd9", logo: "KOTAKBANK.png", p: 1800 },
  { t: "WIPRO", n: "Wipro", c: "#aa66cc", logo: "WIPRO.png", p: 450 },
  { t: "HCLTECH", n: "HCL Technologies", c: "#33b5e5", logo: "HCLTECH.png", p: 1650 },
  { t: "ASIANPAINT", n: "Asian Paints", c: "#ff4444", logo: "ASIANPAINT.png", p: 2300 },
  { t: "MARUTI", n: "Maruti Suzuki", c: "#0099cc", logo: "MARUTI.png", p: 1200 },
  { t: "SUNPHARMA", n: "Sun Pharma", c: "#f78b00", logo: "SUNPHARMA.png", p: 1750 },
  { t: "TITAN", n: "Titan Company", c: "#3e2723", logo: "TITAN.png", p: 3200 },
  { t: "ULTRACEMCO", n: "UltraTech Cement", c: "#ffbb33", logo: "ULTRACEMCO.png", p: 1100 },
  { t: "NTPC", n: "NTPC Limited", c: "#2bbbad", logo: "NTPC.png", p: 350 },
  { t: "NESTLEIND", n: "Nestle India", c: "#c0c0c0", logo: "NESTLEIND.png", p: 2500 },
  { t: "BAJFINANCE", n: "Bajaj Finance", c: "#003366", logo: "BAJFINANCE.png", p: 6800 },
  { t: "ADANIENT", n: "Adani Enterprises", c: "#003d6b", logo: "ADANIENT.png", p: 2900 },
  { t: "POWERGRID", n: "Power Grid Corp", c: "#228b22", logo: "POWERGRID.png", p: 310 },
  { t: "AXISBANK", n: "Axis Bank", c: "#97144d", logo: "AXISBANK.png", p: 1100 },
  { t: "TATAMOTORS", n: "Tata Motors", c: "#0066b2", logo: "TATAMOTORS.png", p: 720 },
  { t: "TECHM", n: "Tech Mahindra", c: "#6c2eb9", logo: "TECHM.png", p: 1650 },
  { t: "JSWSTEEL", n: "JSW Steel", c: "#1a237e", logo: "JSWSTEEL.png", p: 870 },
  { t: "HINDALCO", n: "Hindalco Industries", c: "#bf360c", logo: "HINDALCO.png", p: 620 },
  { t: "GRASIM", n: "Grasim Industries", c: "#4e342e", logo: "GRASIM.png", p: 2600 },
  { t: "CIPLA", n: "Cipla", c: "#0d47a1", logo: "CIPLA.png", p: 1450 },
  { t: "EICHERMOT", n: "Eicher Motors", c: "#b71c1c", logo: "EICHERMOT.png", p: 4700 },
  { t: "APOLLOHOSP", n: "Apollo Hospitals", c: "#1565c0", logo: "APOLLOHOSP.png", p: 6500 },
  { t: "TRENT", n: "Trent Ltd", c: "#004d40", logo: "TRENT.png", p: 5500 },
  { t: "BAJAJ-AUTO", n: "Bajaj Auto", c: "#1a237e", logo: "BAJAJ-AUTO.png", p: 8900 },
  { t: "HDFCLIFE", n: "HDFC Life Insurance", c: "#e91e63", logo: "HDFCLIFE.png", p: 650 },
  { t: "ADANIPORTS", n: "Adani Ports & SEZ", c: "#00695c", logo: "ADANIPORTS.png", p: 1350 },
  { t: "COALINDIA", n: "Coal India", c: "#37474f", logo: "COALINDIA.png", p: 390 },
  { t: "BEL", n: "Bharat Electronics", c: "#1b5e20", logo: "BEL.png", p: 280 },
  { t: "DRREDDY", n: "Dr. Reddy's Labs", c: "#4a148c", logo: "DRREDDY.png", p: 1200 },
  { t: "TATASTEEL", n: "Tata Steel", c: "#263238", logo: "TATASTEEL.png", p: 140 },
  { t: "INDIGO", n: "InterGlobe Aviation", c: "#003580", logo: "INDIGO.png", p: 4600 },
  { t: "SBILIFE", n: "SBI Life Insurance", c: "#1a237e", logo: "SBILIFE.png", p: 1550 },
  { t: "BAJAJFINSV", n: "Bajaj Finserv", c: "#01579b", logo: "BAJAJFINSV.png", p: 1600 },
  { t: "ONGC", n: "Oil & Natural Gas Corp", c: "#e65100", logo: "ONGC.png", p: 240 },
  { t: "JIOFIN", n: "Jio Financial Services", c: "#0d47a1", logo: "JIOFIN.png", p: 320 },
  { t: "SHRIRAMFIN", n: "Shriram Finance", c: "#880e4f", logo: "SHRIRAMFIN.png", p: 580 },
  { t: "ETERNAL", n: "Eternal Ltd", c: "#e53935", logo: "ETERNAL.png", p: 210 },
  { t: "TATACONSUM", n: "Tata Consumer Products", c: "#1565c0", logo: "TATACONSUM.png", p: 1050 },
  { t: "M&M", n: "Mahindra & Mahindra", c: "#d32f2f", logo: "M&M.png", p: 2700 },
  { t: "MAXHEALTH", n: "Max Healthcare", c: "#00838f", logo: "MAXHEALTH.png", p: 950 },
];
